obj-$(CONFIG_DRM_HIX5HD2)	+= hix5hd2-drm.o

hix5hd2-drm-y := hix5hd2_drm_drv.o \
                 hix5hd2_drm_plane.o \
		 hix5hd2_drm_crtc.o \
		 hix5hd2_drm_display.o \
		 hix5hd2_drm_component.o \
		 hix5hd2_drm_hdmi.o
 

